### ISSUE TITLE
リンクを有効化しブラウザで確認できる

### ISSUE THREAD

**Issue by ghost** [TetsuyaNegishi/ngs-ichikawa#116]
## User Story
ユーザとして、回答に含まれるリンクを有効化してほしい。  
手軽にアクセスしたいため。

## Acceptance Criteria
- [x] リンクが有効になっている
- [x] リンクをクリック（タップ）するとブラウザからアクセスできる

## References
[完了定義シート](https://docs.google.com/spreadsheets/d/1FH1Xue3LAR1OYY93sWq4b1zdCq2X80H_A5q_QK_agNc/edit#gid=1478443368)
[npm - autolinker](https://www.npmjs.com/package/autolinker)
[ブラウザ呼び出す](http://phiary.me/cordova-tips-open-system-browser/)
## ToDo
- [x] リンク有効化についての方法調査（フロント、サーバ）
- [x] リンクからブラウザの起動方法を調査(OS 側でやってくれる可能性大）
- [x] 実装
- [x] 実機で確認
