### ISSUE TITLE
ユーザは他の人が投稿した困りごとを閲覧することができる

### ISSUE THREAD

**Issue by TetsuyaNegishi** [TetsuyaNegishi/ngs-ichikawa#119]
## User Story
ユーザは他の人が投稿した困りごとを閲覧することができる

## Acceptance Criteria
- [x] ホーム画面下部に「本人の困りごと」「みんなのこまりごと」タブがある
- [x] 「みんなのこまりごと」タブをタップすれば、みんなの困りごと投稿一覧画面に遷移する
- [x] 「本人の困りごと」タブをタップすれば、本人の困りごと投稿一覧画面に遷移する

## References
[完了定義シート](https://docs.google.com/spreadsheets/u/2/d/1FH1Xue3LAR1OYY93sWq4b1zdCq2X80H_A5q_QK_agNc/edit#gid=1057933700)

## ToDo
- [x] タブを作る
- [x] 本人の困り事ページを作る
- [x] みんなの困り事ページを作る
