### ISSUE TITLE
APIを使ったデータの送受信

### ISSUE THREAD

**Issue by ghost** [TetsuyaNegishi/ngs-ichikawa#24]
# Task
APIを使ってデータの送受信を試す

# ToDo
- [x] https://kaname-senpai.herokuapp.com/problems にGETでアクセスしてみる
- [x] https://kaname-senpai.herokuapp.com/problems にPOSTでデータを送信する 
- [x] 実機（Androidアプリ）で試す
- [x] 画像のアップロード
