### ISSUE TITLE
投稿ページのデザイン改変

### ISSUE THREAD

**Issue by TetsuyaNegishi** [TetsuyaNegishi/ngs-ichikawa#65]
# User Story
投稿ページのデザイン改変

# Acceptance Criteria
- [x] 投稿ページ(写真追加前)がデザイン通りになっている(デザインは完了定義参照)
- [x] 投稿ページ(写真追加後)がデザイン通りになっている(デザインは完了定義参照)
- [x] 写真の☓ボタンをタップして、追加した写真を消せる

# Reference
[完了定義シート](https://docs.google.com/spreadsheets/d/1moNvObKU56e7Ep6z-OBclfU3PoeqIiwlMzuxz-aTP8c/edit#gid=223576975)

# ToDo
- [x] 困りごとのinputを作る(インクリメントできるように)
- [x] 画像の追加ボタンを作る
- [x] バリデーション
- [x] 二重ポストを防ぐ
- [x] ポストボタンを付ける
- [x] キーボードを表示したときの動作を確認

**Comment by TetsuyaNegishi** [comment]
カメラのアイコン：ion-ios-camera-outline
[http://ionicons.com/](http://ionicons.com/)
